sudo: false
language: node_js
node_js :
  - "10.16.2"
  - "10.16.3"
  - "12.11.1"
addons:
  apt:
    packages:
      - libssl-dev
      - liblzma-dev
cache:
  directories:
  - /tmp/htslib
  - /tmp/samtools
  - /tmp/freebayes
  - /tmp/software
env:
  global:
    - MONGODB_VERSION=3.4.3
    - MINICONDA_VERSION="4.6.14"
    - CONDA_GENERIC_CHANNEL="https://dnap.cog.sanger.ac.uk/npg/conda/prod/generic/linux-64/"
    - MINICONDA_HOME="miniconda"
    - FREEBAYES_VERSION="v1.1.0"
    - BIOBAMBAM_VERSION="2.0.72-release-20170316102450"
    - HTSLIB_VERSION="1.5"
    - SAMTOOLS1_VERSION="1.5"
before_install:
  - ./.travis/install.sh
  - export PATH="/tmp/usr/bin:${PATH}"
  - npm install -g grunt-cli
  - npm --version
  - mongo --version
  - conda --version
  - freebayes --version
  - bamstreamingmarkduplicates --version
  - samtools --version
script:
  - grunt -v
